package com.entreck.pos.interfaces;

import com.entreck.event.application.dto.AvailabilityRequest;
import com.entreck.event.application.dto.AvailabilityResponse;
import com.entreck.event.application.usecase.UpdateAvailabilityUseCase;
import com.entreck.pos.application.dto.CreatePointOfSaleRequest;
import com.entreck.pos.application.dto.PointOfSaleDetailResponse;
import com.entreck.pos.application.dto.PointOfSaleResponse;
import com.entreck.pos.application.dto.UpdatePointOfSaleRequest;
import com.entreck.pos.application.usecase.GetPointOfSaleDetailUseCase;
import com.entreck.pos.application.usecase.RegisterPointOfSaleUseCase;
import com.entreck.pos.application.usecase.UpdatePointOfSaleUseCase;
import com.entreck.shared.domain.id.EventId;
import com.entreck.shared.domain.id.PointOfSaleId;
import com.entreck.shared.domain.id.ShopId;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

/**
 * REST controller for PointOfSale endpoints.
 *
 * <p>Maps HTTP requests to use case invocations. Delegates business logic to
 * application-layer use cases; no business rules in this class.
 */
@RestController
@RequestMapping("/api/v1/points-of-sale")
public class PointOfSaleController {

  private final RegisterPointOfSaleUseCase registerPointOfSaleUseCase;
  private final UpdatePointOfSaleUseCase updatePointOfSaleUseCase;
  private final GetPointOfSaleDetailUseCase getPointOfSaleDetailUseCase;
  private final UpdateAvailabilityUseCase updateAvailabilityUseCase;

  /**
   * Constructs the controller with the required use cases.
   *
   * @param registerPointOfSaleUseCase the register-POS use case (S01)
   * @param updatePointOfSaleUseCase the update-POS use case (S02)
   * @param getPointOfSaleDetailUseCase the get-POS-detail use case (B06)
   * @param updateAvailabilityUseCase the update-availability use case (S03)
   */
  public PointOfSaleController(
      RegisterPointOfSaleUseCase registerPointOfSaleUseCase,
      UpdatePointOfSaleUseCase updatePointOfSaleUseCase,
      GetPointOfSaleDetailUseCase getPointOfSaleDetailUseCase,
      UpdateAvailabilityUseCase updateAvailabilityUseCase) {
    this.registerPointOfSaleUseCase = registerPointOfSaleUseCase;
    this.updatePointOfSaleUseCase = updatePointOfSaleUseCase;
    this.getPointOfSaleDetailUseCase = getPointOfSaleDetailUseCase;
    this.updateAvailabilityUseCase = updateAvailabilityUseCase;
  }

  /**
   * Retrieves full point-of-sale detail (B06).
   *
   * @param id the point of sale identifier
   * @return the POS detail response
   */
  @GetMapping("/{id}")
  @ResponseStatus(HttpStatus.OK)
  public PointOfSaleDetailResponse getPointOfSaleDetail(@PathVariable Long id) {
    return getPointOfSaleDetailUseCase.execute(new PointOfSaleId(id));
  }

  /**
   * Registers a new point of sale (S01).
   *
   * <p>In v1, the shop ID is accepted from the request body because
   * authentication is deferred. The POS ID is generated by the database;
   * the adapter replaces any placeholder.
   *
   * @param request the validated create POS request
   * @return the registered POS response with HTTP 201
   */
  @PostMapping
  @ResponseStatus(HttpStatus.CREATED)
  public PointOfSaleResponse registerPointOfSale(
      @Valid @RequestBody CreatePointOfSaleRequest request) {
    // Placeholder ID; the adapter will let JPA generate the real ID
    return registerPointOfSaleUseCase.execute(
        request, new PointOfSaleId(0L), new ShopId(request.shopId()));
  }

  /**
   * Updates an existing point of sale with partial data (S02, ADR-13).
   *
   * @param id the point of sale identifier
   * @param request the validated update request (PATCH semantics)
   * @return the updated POS response
   */
  @PatchMapping("/{id}")
  @ResponseStatus(HttpStatus.OK)
  public PointOfSaleResponse updatePointOfSale(
      @PathVariable Long id,
      @Valid @RequestBody UpdatePointOfSaleRequest request) {
    return updatePointOfSaleUseCase.execute(new PointOfSaleId(id), request);
  }

  /**
   * Updates the availability of an event-POS link (S03, ADR-13).
   *
   * @param posId the point-of-sale identifier
   * @param eventId the event identifier
   * @param request the validated availability request (PUT semantics)
   * @return the updated availability response
   */
  @PutMapping("/{posId}/events/{eventId}/availability")
  @ResponseStatus(HttpStatus.OK)
  public AvailabilityResponse updateAvailability(
      @PathVariable Long posId,
      @PathVariable Long eventId,
      @Valid @RequestBody AvailabilityRequest request) {
    return updateAvailabilityUseCase.execute(
        new EventId(eventId), new PointOfSaleId(posId), request);
  }
}
