package com.entreck.event.interfaces;

import com.entreck.event.application.dto.CreateEventRequest;
import com.entreck.event.application.dto.EventDetailResponse;
import com.entreck.event.application.dto.EventResponse;
import com.entreck.event.application.dto.EventSummaryResponse;
import com.entreck.event.application.dto.UpdateEventRequest;
import com.entreck.event.application.usecase.FindEventsUseCase;
import com.entreck.event.application.usecase.GetEventDetailUseCase;
import com.entreck.event.application.usecase.PublishEventUseCase;
import com.entreck.event.application.usecase.UpdateEventUseCase;
import com.entreck.shared.domain.DomainPage;
import com.entreck.shared.domain.id.EventId;
import com.entreck.shared.domain.id.OrganizerId;
import com.entreck.shared.domain.enums.EventCategory;
import com.entreck.shared.web.PageResponse;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

/**
 * REST controller for Event endpoints.
 *
 * <p>Maps HTTP requests to use case invocations. Delegates business logic to
 * application-layer use cases; no business rules in this class.
 */
@RestController
@RequestMapping("/api/v1/events")
public class EventController {

  private static final int MAX_PAGE_SIZE = 100;

  private final PublishEventUseCase publishEventUseCase;
  private final UpdateEventUseCase updateEventUseCase;
  private final FindEventsUseCase findEventsUseCase;
  private final GetEventDetailUseCase getEventDetailUseCase;

  /**
   * Constructs the controller with the required use cases.
   *
   * @param publishEventUseCase the publish-event use case (O01)
   * @param updateEventUseCase the update-event use case (O02)
   * @param findEventsUseCase the find-events use case (B01, B02)
   * @param getEventDetailUseCase the get-event-detail use case (B03)
   */
  public EventController(
      PublishEventUseCase publishEventUseCase,
      UpdateEventUseCase updateEventUseCase,
      FindEventsUseCase findEventsUseCase,
      GetEventDetailUseCase getEventDetailUseCase) {
    this.publishEventUseCase = publishEventUseCase;
    this.updateEventUseCase = updateEventUseCase;
    this.findEventsUseCase = findEventsUseCase;
    this.getEventDetailUseCase = getEventDetailUseCase;
  }

  /**
   * Searches events with optional filters and pagination (B01, B02).
   *
   * @param name optional name filter
   * @param category optional category filter
   * @param page the 0-based page number (default 0)
   * @param size the page size (default 20, capped at 100)
   * @return a paginated response of event summaries
   */
  @GetMapping
  @ResponseStatus(HttpStatus.OK)
  public PageResponse<EventSummaryResponse> searchEvents(
      @RequestParam(required = false) String name,
      @RequestParam(required = false) EventCategory category,
      @RequestParam(defaultValue = "0") int page,
      @RequestParam(defaultValue = "20") int size) {
    int effectiveSize = Math.min(size, MAX_PAGE_SIZE);
    DomainPage<EventSummaryResponse> result =
        findEventsUseCase.execute(name, category, page, effectiveSize);
    boolean first = result.meta().page() == 0;
    boolean last = result.meta().totalPages() == 0
        || result.meta().page() >= result.meta().totalPages() - 1;
    return new PageResponse<>(result.content(), result.meta(), first, last);
  }

  /**
   * Retrieves full event detail (B03).
   *
   * @param id the event identifier
   * @return the event detail response
   */
  @GetMapping("/{id}")
  @ResponseStatus(HttpStatus.OK)
  public EventDetailResponse getEventDetail(@PathVariable Long id) {
    return getEventDetailUseCase.execute(new EventId(id));
  }

  /**
   * Publishes a new event (O01).
   *
   * <p>In v1, the organizer ID is accepted as a request parameter because
   * authentication is deferred. The event ID is generated by the database;
   * the adapter replaces any placeholder.
   *
   * @param request the validated create event request
   * @param organizerId the organizer creating the event
   * @return the published event response with HTTP 201
   */
  @PostMapping
  @ResponseStatus(HttpStatus.CREATED)
  public EventResponse publishEvent(
      @Valid @RequestBody CreateEventRequest request,
      @RequestParam Long organizerId) {
    // Placeholder ID; the adapter will let JPA generate the real ID
    return publishEventUseCase.execute(request, new OrganizerId(organizerId), new EventId(0L));
  }

  /**
   * Updates an existing event with partial data (O02, ADR-13).
   *
   * @param id the event identifier
   * @param request the validated update request (PATCH semantics)
   * @return the updated event response
   */
  @PatchMapping("/{id}")
  @ResponseStatus(HttpStatus.OK)
  public EventResponse updateEvent(
      @PathVariable Long id,
      @Valid @RequestBody UpdateEventRequest request) {
    return updateEventUseCase.execute(new EventId(id), request);
  }
}
